### ISSUE TITLE
支持Linux和MacOS吗？

### ISSUE THREAD

**Issue by ywxt** [weolar/miniblink49#100]
支持Linux和MacOS吗？如果现在不支持，那么支持的打算吗？因为体积小，所以打算用它来开发一个跨平台的桌面应用。

**Comment by ywxt** [comment]
因为体积小，所以打算用它来开发一个跨平台的桌面应用。

**Comment by weolar** [comment]
暂不支持，因为目前好像这方面需求较少…

**Comment by lexesv** [comment]
I really need Linux version
