### ISSUE TITLE
点击网页弹出框中的按钮无反应

### ISSUE THREAD

**Issue by Tinide** [weolar/miniblink49#105]
![1](https://user-images.githubusercontent.com/35944766/41843824-13e86bbc-78a1-11e8-82b7-5ec321aeec95.png)

如图 点击“立即前往”或者“返回” 都无反应
测试网址:http://online.icinfo.cn/eppnet/home/enHomeAction.do?_id=1529920626960

**Comment by weolar** [comment]
需要账户密码，我这边无法测试

**Comment by Tinide** [comment]
账号:zheng123456 密码123456  测试地址http://online.icinfo.cn/eppnet/
我刚才又试了下用您编译的node.dll(180522)这个版本就可以，我下载最新的源码自己编译的node.dll就不行,怀疑是我编译的有问题但是编译配置什么的我都没动过下载下来我就直接编译的，后来又下载您编译的最新的node.dll(180628)这个版本，发现也不行。怀疑是你后来的版本把什么去掉了，影响了这个功能。

**Comment by weolar** [comment]
你看下dbgview有打印出什么信息吗？

**Comment by Tinide** [comment]
点击是dbugview没有输出任何信息

**Comment by weolar** [comment]
你试试把跨域开关关闭

**Comment by Tinide** [comment]
关闭跨域可以

**Comment by weolar** [comment]
佩服，两年后才来回复…
