### ISSUE TITLE
项目名字的由来?49数字的由来?

### ISSUE THREAD

**Issue by asiontang** [weolar/miniblink49#108]
为啥要加上49这个数字?
第一次发现这个项目,下意识的认为是基于49版本精简而来的.所以才有此疑惑.

**Comment by cppfuns** [comment]
基于chrome版本49裁剪的

**Comment by asiontang** [comment]
看这篇介绍的文章,还以为会一直追跟chromium最新版本呢.看来误会了.
[屌炸天的内核来袭，史上最小chromium内核miniblink！](https://zhuanlan.zhihu.com/p/22611497?group_id=764036386641707008) 
>其基于chromium**最新**版内核，去除了chromium所有多余的部件，只保留最基本的排版引擎blink。

**Comment by weolar** [comment]
有个最新版本的，没放出来。之所以还在用49，是因为这个是最后一个保留npapi的版本
