### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by zydxhs** [weolar/miniblink49#111]
2018-05-25 以后的版本，我这都编译失败。
全部错误提示都是 “error LNK2001: 无法解析的外部符号 "public: class v8::xxx”，类似的提示都在 v8 名称空间。
好像是没有链接 V8 的库。但工程设置中确实有 v8 的库。v8_5_7 工程配置中加了 BUILD_V8_SHARED 宏，这是要构建 动态库 的节奏？但其工程配置又指明构建静态库，miniblink工程配置中也没有添加 USING_V8_SHARED 宏，实在是搞不懂。

有请明白人解答下疑惑。

**Comment by weolar** [comment]
不清楚，没碰到过

**Comment by weolar** [comment]
你是编译release_vc6这个配置吗？

**Comment by zydxhs** [comment]
Relase 版本。release_vc6 没有验证。

**Comment by zydxhs** [comment]
补充部分编译提示：
1>------ 已启动生成: 项目: miniblink, 配置: Release Win32 ------
1>LINK : warning LNK4075: 忽略“/INCREMENTAL”(由于“/LTCG”规范)
1>    正在创建库 e:\miniblink49\build\..\out\Release\node.lib 和对象 e:\miniblink49\build\..\out\Release\node.exp
1>SVGViewSpec.obj : error LNK2001: 无法解析的外部符号 "public: static class v8::Isolate * __cdecl v8::Isolate::GetCurrent(void)" (?GetCurrent@Isolate@v8@@SAPAV12@XZ)
1>v8_5_7.lib(stub-cache.obj) : error LNK2001: 无法解析的外部符号 "public: static class v8::Isolate * __cdecl v8::Isolate::GetCurrent(void)" (?GetCurrent@Isolate@v8@@SAPAV12@XZ)
1>SVGTextPathElement.obj : error LNK2001: 无法解析的外部符号 "public: static class v8::Isolate * __cdecl v8::Isolate::GetCurrent(void)" (?GetCurrent@Isolate@v8@@SAPAV12@XZ)
1>SVGTextPositioningElement.obj : error LNK2001: 无法解析的外部符号 "public: static class v8::Isolate * __cdecl v8::Isolate::GetCurrent(void)" (?GetCurrent@Isolate@v8@@SAPAV12@XZ)

1>V8AutocompleteErrorEvent.obj : error LNK2001: 无法解析的外部符号 "public: bool __thiscall v8::Value::IsInt32(void)const " (?IsInt32@Value@v8@@QBE_NXZ)
1>V8AutocompleteErrorEventInit.obj : error LNK2001: 无法解析的外部符号 "public: bool __thiscall v8::Value::IsInt32(void)const " (?IsInt32@Value@v8@@QBE_NXZ)
1>V8AnimationEventInit.obj : error LNK2001: 无法解析的外部符号 "public: bool __thiscall v8::Value::IsInt32(void)const " (?IsInt32@Value@v8@@QBE_NXZ)

1>v8_5_7.lib(code-generator-ia32.obj) : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: static class v8::internal::ExternalReference __cdecl v8::internal::ExternalReference::ieee754_tanh_function(class v8::internal::Isolate *)" (__imp_?ieee754_tanh_function@ExternalReference@internal@v8@@SA?AV123@PAVIsolate@23@@Z)
1>v8_5_7.lib(code-generator-ia32.obj) : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) protected: virtual void __thiscall v8::internal::MathPowIntegerDescriptor::InitializePlatformSpecific(class v8::internal::CallInterfaceDescriptorData *)" (__imp_?InitializePlatformSpecific@MathPowIntegerDescriptor@internal@v8@@MAEXPAVCallInterfaceDescriptorData@23@@Z)
1>e:\miniblink49\build\..\out\Release\mb.dll : warning LNK4088: 因 /FORCE 选项生成了映像；映像可能不能运行
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by weolar** [comment]
不要编译release版，很久没管那个了

**Comment by zydxhs** [comment]
release_vc6 也存在同样的问题。
1>------ 已启动生成: 项目: miniblink, 配置: Release_vc6 Win32 ------
1>    正在创建库 e:\miniblink49\build\..\out\Release_vc6\node.lib 和对象 e:\miniblink49\build\..\out\Release_vc6\node.exp
1>SVGViewSpec.obj : error LNK2001: 无法解析的外部符号 "public: static class v8::Isolate * __cdecl v8::Isolate::GetCurrent(void)" (?GetCurrent@Isolate@v8@@SAPAV12@XZ)
1>SVGTextPathElement.obj : error LNK2001: 无法解析的外部符号 "public: static class v8::Isolate * __cdecl v8::Isolate::GetCurrent(void)" (?GetCurrent@Isolate@v8@@SAPAV12@XZ)

代码是最新的（a587882）。
编译顺序(miniblink工程配置中，去掉 v8_5_7_1.lib )：
1. libcurl+libjpeg+libpng+libxml+openssl+ots+skia+v8_5_7+wolfssl+zlib
2. miniblink

**Comment by weolar** [comment]
难怪，你把v8_5_7_1.lib 去掉了当然编译不过了

**Comment by zydxhs** [comment]
v8_5_7 与 v8_5_7_1 不同一份代码吗，怎么需要编译两次？这太怪异了

**Comment by zydxhs** [comment]
现在剩下最后一个错误了：
1>------ 已启动生成: 项目: miniblink, 配置: Release_vc6 Win32 ------
1>    正在创建库 e:\miniblink49\build\..\out\Release_vc6\node.lib 和对象 e:\miniblink49\build\..\out\Release_vc6\node.exp
1>wke.obj : error LNK2001: 无法解析的外部符号 "public: static void __cdecl blink::WebCustomElement::addEmbedderCustomElementName(class blink::WebString const &)" (?addEmbedderCustomElementName@WebCustomElement@blink@@SAXABVWebString@2@@Z)
1>e:\miniblink49\build\..\out\Release_vc6\miniblink.dll : fatal error LNK1120: 1 个无法解析的外部命令
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by weolar** [comment]
你自己把这个文件加到工程吧。我这边代码还没提交完
