### ISSUE TITLE
使用教程？

### ISSUE THREAD

**Issue by chenyihao2621023** [weolar/miniblink49#119]
只是一个小前端，表示看不懂。。。api和elctron一样，但是具体该怎么使用呢？用npm 装吗？萌新问题，希望不吝赐教

**Comment by juhuaguai** [comment]
这种情况可以考虑加入群，在群里交流。。。

**Comment by chenyihao2621023** [comment]
谢谢， 我加群了， 可是群满了。。。

**Comment by weolar** [comment]
现在群号 是94093808。没满吧，不过我设置要付费一毛钱才能进…

**Comment by chenyihao2621023** [comment]
满啦。。。我刚试的 已经218个人啦 可以升级下人数吗

**Comment by weolar** [comment]
我明白了，我的会员昨天过期了，这腾讯……

**Comment by weolar** [comment]
你再试试
