### ISSUE TITLE
miniblink js对象 localStorage 删除和清理有问题

### ISSUE THREAD

**Issue by devin87** [weolar/miniblink49#123]
1. 删除（localStorage.removeItem）和清理（ localStorage.clear），当时有效，但刷新页面就恢复到之前的状态，每次都能重现。
2. 设置貌似也有问题，有时候设置不成功，有时候键值都反了，暂未重现。

**Comment by weolar** [comment]
1，我试试
2，设置找到重现方式告诉我一下
