### ISSUE TITLE
cookies.dat文件读写可能会很频繁, 当放在U盘上使用时, 会影响速度

### ISSUE THREAD

**Issue by rzhghost** [weolar/miniblink49#125]
由于网站比较复杂, 特别是多点登录的网站, 会反复快速的读写cookies.dat, 当放在u盘上用时, 非常影响页面的加载速度,建议有参数可调整是内存中处理cookies还是以文件的方式来处理

**Comment by weolar** [comment]
好的

**Comment by rzhghost** [comment]
确实如此,可以变通解决
