### ISSUE TITLE
2018-7-23 release版编译不过~~

### ISSUE THREAD

**Issue by wzaen** [weolar/miniblink49#134]
Cannot open source file: '..\..\net\ActivatingLoaderCheck.cpp'

https://codeload.github.com/weolar/miniblink49/zip/2018-7-23

**Comment by zero-rp** [comment]
神僧漏提代码了,等他提上来再编译,神僧经常干这个事,习惯了就好

**Comment by wzaen** [comment]
还有什么是需要注意的？囧

**Comment by xuxian02092213** [comment]
我发现最新版本编译不过，貌似原来的一个cpp和.h被替换掉了，prj工程中未替换，具体为：
ActivatingObjCheck.cpp为新增
ActivatingLoaderCheck文件已经不存在
另外工程中还需要增加third_party\WebKit\Source\web\WebStorageEventDispatcherImpl.cpp
文件才可以保证编译通过
但不知道是不是还缺少其他的东西。我这边编译通过了
