### ISSUE TITLE
miniblink封装到一个ActiveX中，滑动鼠标，会导致程序崩溃

### ISSUE THREAD

**Issue by xuxian02092213** [weolar/miniblink49#147]
我把miniblink封装到了ActiveX中，滑动鼠标，改变鼠标的时候，会触发::PostMessage(m_hWnd, WM_SETCURSOR, 0, 0);
但是MFC中貌似存在bug,在
![image](https://user-images.githubusercontent.com/7521318/43750853-dcd657a8-9a2c-11e8-87c7-1573826e4dd2.png)
CRectTracker::SetCursor方法中
wparam参数为0，强制转换成CWnd*，在使用指针前，未判断指针是否为空，直接使用，导致程序崩溃。
我在上层windowproc中获取WM_SETCURSOR消息，给予wparam=上层窗口句柄，程序不会异常。
我看到发送消息的地方，是否可以把此处发送消息修改为::PostMessage(m_hWnd, WM_SETCURSOR, (WPARAM)m_hWnd, 0);

**Comment by weolar** [comment]
你可以把你封装的activex的代码整理一个能重现的demo，发我调试下。

**Comment by xuxian02092213** [comment]
[blinkbrowser.zip](https://github.com/weolar/miniblink49/files/2265044/blinkbrowser.zip)
blinkbrowserCtrl.cpp 第223行增加的代码，注释掉这个，就会异常。
工程编译出来的是ocx，需要注册下，ocx与node.dll在同一个目录，然后使用tstcon加载blinkbrowser，执行OpenWebUrl 方法，参数www.baidu.com
鼠标滑过页面上，切换鼠标指针后，会异常

**Comment by weolar** [comment]
![111](https://user-images.githubusercontent.com/6235154/43758836-ec6751f4-9a4f-11e8-9c96-11abb4c254b1.jpg)
我这边貌似没发现崩溃

**Comment by weolar** [comment]
https://github.com/weolar/miniblink49/releases/tag/18-8-7

不如你下载今天的最新版本，崩溃了抓个dump给我

**Comment by xuxian02092213** [comment]
你blinkbrowserCtrl.cpp 第223行代码注释掉，然后鼠标在百度一下按钮上下移动下看看看，移除按钮的时候，会改变鼠标指针

**Comment by xuxian02092213** [comment]
新版本编译不过呢

**Comment by xuxian02092213** [comment]
另外访问http://www.bootcss.com/网站
![image](https://user-images.githubusercontent.com/7521318/43763816-532208e0-9a5e-11e8-8825-eee0b81bbafd.png)
就会崩溃

**Comment by weolar** [comment]
我这依然没崩溃。你是不是装了什么npapi插件？

**Comment by weolar** [comment]
你用最新版抓个dump吧。miniblink很久没看到崩溃了

**Comment by xuxian02092213** [comment]
我抓了一个minidump，windbg抓的，我放到群里面可以吗？我的程序是vs2010开发的，node.dll是2017的，我有安装过vlc,vlc貌似会自带npapi插件的把。
访问bootcss网站异常，我截图如下：
![image](https://user-images.githubusercontent.com/7521318/43769565-9d80393a-9a6c-11e8-98af-7c48b16155f3.png)

**Comment by xuxian02092213** [comment]
![image](https://user-images.githubusercontent.com/7521318/43770068-deb20a72-9a6d-11e8-875b-13ce3c1f9422.png)
这个是我登录www.baidu.com,鼠标先放到“百度一下”,然后移除按钮，使用的就是我给你的那个封装的ActiveX,
用VS2010抓到的堆栈：
![image](https://user-images.githubusercontent.com/7521318/43770188-38d91e8c-9a6e-11e8-974b-c75ae1717e1b.png)
往上一层堆栈：
![image](https://user-images.githubusercontent.com/7521318/43770228-5b51e57a-9a6e-11e8-809a-7019dfe9eae1.png)
指针无效

**Comment by weolar** [comment]
1，我猜是mb内部发送了一个::PostMessage(m_hWnd, WM_SETCURSOR, 0, 0);消息（在WebPageImpl::didChangeCursor）
这是我通知host窗口改变光标用的。
2，崩溃的问题应该是vlc插件导致的。我看看怎么解决

**Comment by xuxian02092213** [comment]
::PostMessage(m_hWnd, WM_SETCURSOR, 0, 0);是否可以直接使用SetCursor来替代呢？

**Comment by weolar** [comment]
应该按照windows的格式要求发送WM_SETCURSOR就没问题了。我内部改改看

**Comment by weolar** [comment]
果然是这个原因。下个版本我修复掉。你那边可以临时用wParam = (WPARAM)m_hWnd;的方式规避下

**Comment by xuxian02092213** [comment]
好的
