### ISSUE TITLE
HOOK Websocket是否可以实现?

### ISSUE THREAD

**Issue by rzhghost** [weolar/miniblink49#150]
是否可以像LoadUrlBegin和LoadUrlEnd一样, 对websocket也处理一下,加一个事件, 可以处理socket句柄,
对websocket的发送和接收的数据进行拦截或修改

**Comment by kgsoft** [comment]
这个太奢侈了^_^

**Comment by rzhghost** [comment]
已解决!结案

**Comment by lexesv** [comment]
> 已解决!结案

Tell me please, how you solved this problem?
