### ISSUE TITLE
mini blink对于rebase方面怎么考虑？

### ISSUE THREAD

**Issue by lktc420** [weolar/miniblink49#152]
mini blink对于rebase方面怎么考虑？会更新blink的代码吗？我看最新的chromium code把blink改的爹妈都不认识了。。

**Comment by weolar** [comment]
暂时不考虑rebase，目前内核已经满足绝大部分需求了。而且我还把内核的v8升级到5.7版本，es6的语法都支持。
新版chromium唯一比较吸引我的地方是有gird布局，不过这个目前大家用的不多。
其实miniblink有个chromium57的版本，没开放出来。
