### ISSUE TITLE
输入框光标细节问题

### ISSUE THREAD

**Issue by Kigoal** [weolar/miniblink49#155]
当光标处于输入框末尾中时 方向键→ 会做移动一位
![gif](https://user-images.githubusercontent.com/21240282/44296237-08008200-a2ed-11e8-98df-daea91b99b55.gif)
![gif2](https://user-images.githubusercontent.com/21240282/44296238-08008200-a2ed-11e8-91de-91164af5398f.gif)

**Comment by weolar** [comment]
可能是中文换行和断句规则出了点小问题，感觉影响不大，暂时先放一放。
