### ISSUE TITLE
高DPI细节问题

### ISSUE THREAD

**Issue by Kigoal** [weolar/miniblink49#156]
当设置 wkeSetZoomFactor 大于 1.0 时：
select和tip窗口没有继承缩放；
Element样式尺寸会进行小数取整，例如 1.75缩放时 1px渲染成1px /10px渲染成17px。chrome是四舍五入，edge是渲染一个半透明的1px

**Comment by WeiqiChenZY** [comment]
此处的Element是不是指窗口滚动条之类的其它元素？

**Comment by weolar** [comment]
@WeiqiChenZY 是的。这块还没撸上
