### ISSUE TITLE
HTTP DELETE请求 body部分为空

### ISSUE THREAD

**Issue by liuyanjun0416** [weolar/miniblink49#164]
使用miniblink-180822下载包中的fast-mb.exe 和 wkexe.exe 发送HTTP DELETE请求body内容为空，fast-mb.exe 和 wkexe.exe 的 devtools 中 Network Request payload能看到数据。

**Comment by weolar** [comment]
貌似delete请求部分我还没实现，用到的太少了。你有测试网址吗？

**Comment by liuyanjun0416** [comment]
http://120.77.248.186:3800
![_20180914183148](https://user-images.githubusercontent.com/14315714/45545306-80a32180-b84c-11e8-8780-e443d70b08a3.png)
左边为新版chrome，右边为miniblink-180913 wkexe.exe

**Comment by weolar** [comment]
好的

**Comment by weolar** [comment]
已修复：https://github.com/weolar/miniblink49/releases

**Comment by liuyanjun0416** [comment]
thx~
