### ISSUE TITLE
x64环境

### ISSUE THREAD

**Issue by w136111526** [weolar/miniblink49#165]
请问这个node.dll或者wke.dll，有用vs2015编译x64位的么？

**Comment by weolar** [comment]
有，你可以加群，群共享有

**Comment by w136111526** [comment]
可以，非常感谢

**Comment by donglu** [comment]
用vs2017 直接打开build 里面sln就能编译吗

**Comment by weolar** [comment]
@donglu 没试过vs2017，不过应该可以

**Comment by fangmin860** [comment]
用vs2013 能编译miniblink.sln吗
node.dll有vs2013编译的64位版本吗
是QQ群吗？群号多少呢？

**Comment by weolar** [comment]
@fangmin860 没试过2013.
你可以加群94093808
