### ISSUE TITLE
0915版本的mb，xp操作系统，在程序关闭的时候。mb会弹出提示“禁止初始化前调用此接口:wkeFinalize”

### ISSUE THREAD

**Issue by JackChenLucky** [weolar/miniblink49#166]
0915版本的mb，xp操作系统，在程序关闭的时候。mb会弹出提示“禁止初始化前调用此接口:wkeFinalize”,之前的版本不会，原因是因为我再程序退出的时候。调用了wkeShutdown。如果神僧觉得没有问题就关闭吧。反正我吧这段代码取消掉了。只是2个版本有点不同。

**Comment by weolar** [comment]
wkeShutdown和wkeFinalize其实是同一个函数。你调用完其中一个，另外个当然不能再调用了
