### ISSUE TITLE
css3 flex属性导致justify-content失效

### ISSUE THREAD

**Issue by liuyanjun0416** [weolar/miniblink49#167]
css3 flex布局时，当子元素使用了flex属性时，导致justify-content属性失效。测试页面:http://120.77.248.186:3800/

![_20180917180717](https://user-images.githubusercontent.com/14315714/45617324-8bf08a00-baa4-11e8-9dd2-b81d9fb899e3.png)

**Comment by weolar** [comment]
已修复，下个版本带出
