### ISSUE TITLE
加载页面的时会闪白

### ISSUE THREAD

**Issue by wrapbin** [weolar/miniblink49#177]
WKE 不会。请解决。

**Comment by zhanjx1314** [comment]
请到群里发红包😄。

发自我的 iPhone



在 2018年9月29日，下午6:10，wrapbin <notifications@github.com<mailto:notifications@github.com>> 写道：


WKE 不会。请解决。

**Comment by weolar** [comment]
改个毛。没描述没重现方案，谁知道是不是你自己的问题。
爱用用，反正我也不改。不用别逼逼。
