### ISSUE TITLE
在部分XP系統中無法初始化 (試圖載入格式錯誤的程式)

### ISSUE THREAD

**Issue by wingyukyuk** [weolar/miniblink49#198]
**查到原因了， 謝謝各位。**

//--------------------------------------------

Build .Net 2.0
Windows XP SP3 (x86)

有部分xp可以的， 但有部分又不能。 未能知道兩者的區別。
開發經驗尚淺， 未能得悉原因。
還望可以幫忙， 謝謝。

//////////////////////////////////////////////////////////////////////////
System.BadImageFormatException: 試圖載入格式錯誤的程式。 (發生例外狀況於 HRESULT: 0x8007000B)
   於 MiniBlinkPinvoke.BlinkBrowserPInvoke.wkeInitialize()
   於 MiniBlinkPinvoke.BlinkBrowser.CreateCore()
   於 MiniBlinkPinvoke.BlinkBrowser.OnCreateControl()

**Comment by weolar** [comment]
你是用哪个版本的？
https://github.com/weolar/miniblink49/releases 可以在这下载最新版的dll替换进去试试

**Comment by wingyukyuk** [comment]
感謝你的回覆， 已經找到原因了。 原因是因為網絡問題導致傳送至部分電腦的 dll檔案損毀....
用的是最新版本。
完全沒有留意這個問題就在不停的對比不同xp電腦其他方面的不同。 因為網絡非常慢， 所以從來沒有想過重新下載。

感謝你的回應和協助。
