### ISSUE TITLE
fast-mb.exe视频支持的有问题？

### ISSUE THREAD

**Issue by wzaen** [weolar/miniblink49#203]
新浪的视频用fast-mb.exe打开无法播放，不知道是否没完全支持？
http://news.sina.com.cn/zxt/#269821318

**Comment by wzaen** [comment]
另，181119版，貌似能播放的视频有两个控制条~~
http://www.w3school.com.cn/tiy/t.asp?f=html5_video_all

**Comment by wzaen** [comment]
![default](https://user-images.githubusercontent.com/24803718/48758132-f78be900-ecd9-11e8-9bbd-c08eed837fd6.png)

**Comment by weolar** [comment]
@wzaen 第一个问题，我发现是flash版本的原因。我换了20版本就可以播放了

**Comment by weolar** [comment]
@wzaen 第二个问题今天的新版已经修复
