### ISSUE TITLE
使用node_v8_4_8.dll打开http://fm.taihe.com/奔溃

### ISSUE THREAD

**Issue by dfangboy** [weolar/miniblink49#208]
使用node_v8_4_8.dll打开http://fm.taihe.com/奔溃
采用demo_src修改wWinMain里面的node.dll为node_v8_4_8.dll 运行打开 wkeBrowser 输入 http://fm.taihe.com/后奔溃
node.dll正常

**Comment by weolar** [comment]
用node.dll吧，这个没崩溃

**Comment by weolar** [comment]
已修复
