### ISSUE TITLE
WebGL支持

### ISSUE THREAD

**Issue by zouyaoji** [weolar/miniblink49#216]
我测试了，应该是不支持WebGL的。
请问会考虑或者能支持WebGL吗？

**Comment by weolar** [comment]
暂不考虑了。单线程，还要做webgl动画，性能肯定没法用

**Comment by KnIfER** [comment]
怎么开多线程，不改代码可以开么。我要给markdown渲染器用，单线程太卡了。。。
@weolar

**Comment by weolar** [comment]
@KnIfER 你放到另外个线程就行了

**Comment by KnIfER** [comment]
怎么放啊，我试过吧dll加载、实例化全都放到另一个线程，然后排列组合，还是不行。

你以前说过把blink线程、ui线程分开，这个难不？

**Comment by KnIfER** [comment]
mb.dll虽然是多线程渲染，但是卡住的JS会持续运行，运行完后才会加载新的页面。

**Comment by KnIfER** [comment]
加载的自定义bytes会被回收啊，额

**Comment by KnIfER** [comment]
mbLoadHtmlWithBaseUrl 加载的字符串会被回收？

**Comment by KnIfER** [comment]
“单线程”可以是特性，比如用制作一个用JS批量将HTML文件转换为markdown文档的编辑器插件，如果是多线程执行JS脚本的话，时机不好控制，更适合用单线程运行。
