### ISSUE TITLE
是否可以去掉图片上面右键菜单的“复制图片”功能

### ISSUE THREAD

**Issue by harry0703** [weolar/miniblink49#224]
是否可以去掉图片上面右键菜单的“复制图片”功能

![image](https://user-images.githubusercontent.com/4928832/50823575-43205200-136f-11e9-886c-46ad2c429c93.png)

**Comment by weolar** [comment]
这个可以通过注入js去掉，把contextmenu禁用就行了

**Comment by harry0703** [comment]
> 这个可以通过注入js去掉，把contextmenu禁用就行了

已解决，非常感谢！
