### ISSUE TITLE
xp 兼容问题

### ISSUE THREAD

**Issue by 96chh** [weolar/miniblink49#225]

**Comment by 96chh** [comment]
我写了一个嵌入 qt 的小 Demo，[mbTest](https://github.com/96chh/mbTest)，然后通过 windeployqt 命令打包，在 win7 运行正常，xp 下报错，用的是目前 mb 最新版本。
![image](https://user-images.githubusercontent.com/22561878/51317981-fc7bd780-1a93-11e9-9aa4-bb94855073f0.png)

windeployqt 命令打包后的目录：
![image](https://user-images.githubusercontent.com/22561878/51318150-790eb600-1a94-11e9-8fab-24675b7f7acd.png)

希望大佬们有空能指点一二，谢谢！

**Comment by 96chh** [comment]
不好意思，路径问题弄错了。。。

**Comment by weolar** [comment]
好的……
