### ISSUE TITLE
Context Menu Language

### ISSUE THREAD

**Issue by Natulux** [weolar/miniblink49#226]
I tried to change the standard language, because even here in europe the standard charset is chinese (maybe GB18030).

I used:
wkeSetLanguage(m_webview, "UTF-8"); 
And also tried:
wkeSetLanguage(m_webview, "ISO-8859-1"); //Latin-1
Both made google.com to load in my language, but if I use a right click, the context menu is still with chinese letters. Is there another option to set the language that I didn't see?

Or can you tell me, in which file/class or function I can edit the content of the context menu?

Thanks
Natu

**Comment by weolar** [comment]
oh..I do not  implement english context menu, but you can edit the source code in content/ui/ContextMeun.h,  ContextMenu::show to change the text.
I will implement english version in the future.

**Comment by Natulux** [comment]
ok, thank you!

**Comment by leventuncu** [comment]
Also I need in different language (turkish). could you please more generic solution when you make changes to implement english context menu? 
Thanks in advance
