### ISSUE TITLE
禁止多线程调用wkeRunJSW，如何解决？

### ISSUE THREAD

**Issue by Coolkkmeat** [weolar/miniblink49#228]
如题，程序需要多线程从网络获取数据，后调用一个总体回调函数，在回调函数中会使用wkeRunJSW，该如何是好？？

**Comment by weolar** [comment]
把任务抛到主线程就行了，很多方式，比如窗口消息

**Comment by weolar** [comment]
把任务抛到主线程就行了，很多方式，比如窗口消息
