### ISSUE TITLE
Miniblink49不支持Css原生变量

### ISSUE THREAD

**Issue by litlight** [weolar/miniblink49#231]
通过测试Chrome49.0.2623.75，可以支持Css3原生变量，Css3变量又称Css自定义属性。
CSS中原生的变量定义语法是：--* ，变量使用语法是：var(--* )，其中*表示我们的变量名称。
例如：
:root {
  --1: #369;
}
body {
  background-color: var(--1);
}
此时背景颜色会显示深蓝色

在Chrome49.0.2623.75的控制台下，执行如下代码可以成功添加并取回原生变量
var element=document.getElementsByTagName("body")
element[0].style.setProperty("--hello", "world")
var myhello = element[0].style.getPropertyValue("--hello");
console.log(myhello)

在miniblink下，使用自带wke.exe或者编译程序，在控制台下无法添加原生变量，返回值为null。
在调试模式的Elements界面下：
:root {
  --1: #369; // 错误，提示Unknown property name.
}

body {
  background-color: var(--1); // 错误，提示Invalid property value.
}
Miniblink是一个非常强大的界面平台，真心点赞。同时Css原生变量对于界面设计和实现有很大的帮助。希望能够添加上本功能。

**Comment by weolar** [comment]
以后考虑加上，这个改动比较大

**Comment by litlight** [comment]
最新发布版19-3-19，已经支持CSS Variable，功能强大，非常完美。

万分感谢！！！
