### ISSUE TITLE
这么多个版本过去了，还是无法显示支付宝支付二维码

### ISSUE THREAD

**Issue by sonyps5201314** [weolar/miniblink49#235]
http://ry.foxuc.net/Pay/ZFB/Alipay.aspx
![image](https://user-images.githubusercontent.com/20564099/53002097-d8caf900-3466-11e9-994f-94fc5789aed4.png)
其他浏览器就可以
![image](https://user-images.githubusercontent.com/20564099/53002152-f304d700-3466-11e9-9fa4-a9264cd575fc.png)

**Comment by weolar** [comment]
你试试最新版本呢

**Comment by sonyps5201314** [comment]
也还是不行啊，我看近期你没改这方面的问题啊。测试了还是不行的。
你注册个号，尝试充值试试啊，二维码都出不来，不会扣你钱的。

**Comment by prownsix** [comment]
遇到同样问题，测试了最新版20190308也是无效，求助

**Comment by sonyps5201314** [comment]
> 遇到同样问题，测试了最新版20190308也是无效，求助
还是放弃吧，这么多问题，一点不稳定，作者也只顾改自己的，用户提出了这么多问题选择视而不见。

**Comment by XLJ707781299** [comment]
你好，我现在出现支付宝支付二维码无法显示的问题，目前这个问题怎么处理呢

**Comment by weolar** [comment]
@XLJ707781299 你是什么版本呢？

**Comment by XLJ707781299** [comment]
@weolar  使用的是最新的miniblink-190527
![QQ截图20190529150211](https://user-images.githubusercontent.com/18643987/58536448-2784ed80-8223-11e9-97d2-588aeffe4ed5.png)
![QQ截图20190529150448](https://user-images.githubusercontent.com/18643987/58536449-28b61a80-8223-11e9-86a6-4e00d5e0f5c2.png)
