### ISSUE TITLE
崩溃BUG

### ISSUE THREAD

**Issue by nuoyan001** [weolar/miniblink49#240]
访问 https://signin.ebay.com.hk/ws/eBayISAPI.dll?SignIn&ru=https%3A%2F%2Fwww.ebay.com.hk%2F
或: https://reg.ebay.com.hk/reg/PartialReg?ru=https%3A%2F%2Fwww.ebay.com.hk%2F
依旧崩溃
VIP DOME也一样

**Comment by weolar** [comment]
已修复。下个版本带出

**Comment by nuoyan001** [comment]
太好了,希望能解决问题.我希望能买个人版使用

**Comment by weolar** [comment]
好啊，目前你就是这个bug需要解决吧？

**Comment by nuoyan001** [comment]
就的,目前来说就是这个问题,期待中

**Comment by weolar** [comment]
https://jp002edupl-my.sharepoint.com/:u:/g/personal/miniblink_office2016_live/EXXjKJc2nJFPlbgqLTcpzNwB8w74WmTiAWa8dNaVPmRoVQ?e=hDACdg
你试试能否下载

**Comment by nuoyan001** [comment]
收到了,我已经测试过了,不崩溃了,不知道是不是我单线程的问题,加载会比较慢
我应该怎么去购买呢?

**Comment by nuoyan001** [comment]
请查收我的申请邮件
