### ISSUE TITLE
默认字体和和系统的不一样

### ISSUE THREAD

**Issue by sosopop** [weolar/miniblink49#241]
下面是和chrome的比较，或者怎么设置默认字体
miniblink
![image](https://user-images.githubusercontent.com/3153828/53480427-27efda00-3ab6-11e9-8b35-cbdaa4b990ad.png)
chrome
![image](https://user-images.githubusercontent.com/3153828/53480549-6a191b80-3ab6-11e9-9983-15a298429191.png)

**Comment by gjl8820** [comment]
同样遇到了 换成老版本就正常，新版本没发现哪里可以设置字体

**Comment by zero-rp** [comment]
请使用wkeSetDebugConfig接口设置默认字体,具体参考文档[http://miniblink.net/doc-main.html](url)
