### ISSUE TITLE
miniblink Devtools 空白

### ISSUE THREAD

**Issue by mrlong** [weolar/miniblink49#242]
Delphi 开发的。

**Comment by mrlong** [comment]
为何没有回答，是不是收费版才能回复？

**Comment by song0320** [comment]
我也碰到了

**Comment by yaphone** [comment]
请问这个问题解决了吗

**Comment by weolar** [comment]
我没碰到过，请问是怎么出现的？

**Comment by yaphone** [comment]
> 我没碰到过，请问是怎么出现的？

好像是mb.dll版本不匹配，换老版本后问题解决

**Comment by zero-rp** [comment]
请使用 wkeSetDebugConfig(view, "showDevTools", utf8 path);设置调试资源路径

**Comment by KnIfER** [comment]
wkeShowDevtools(mWebView, L"C:\\tmp\\miniblink-20200824\\front_end\\inspector.html", 0, 0);

@weolar 可以打开远程页面调试工具吗？调试安卓手机的那种。
