### ISSUE TITLE
建议改用 chromium 原生的 gn 与 ninja build

### ISSUE THREAD

**Issue by VigorFox** [weolar/miniblink49#248]
现在官方的 chromium 的 windows 版本也是使用 gn 生成 vs 的工程文件，同时也使用 ninja + clang-cl 编译。建议跟官方做法同步，这样能更好的实现跨平台开发。

**Comment by zero-rp** [comment]
官方的gn用起来不方便,跨平台会使用cmake处理,所以不考虑使用gn
