### ISSUE TITLE
Miniblink能否支持await async方法

### ISSUE THREAD

**Issue by litlight** [weolar/miniblink49#253]
miniblink最新的v8引擎使用6.7，网上有资料介绍v8在6.6版本中，就已经加入了async和await的支持。
而且v8_6_7目录下，搜索await字符串，也可以得到关于await实现的代码。
但是目前在控制台中调用await显示Uncaught ReferenceError: await is not defined
是否可以通过 harmony-async-await这样的开关量启用这个功能？

**Comment by weolar** [comment]
你是用node.dll还是node_4_8.dll？node.dll已经实现await了

**Comment by litlight** [comment]
您好，我用的是node.dll，编译时连接的是v8_5_7.lib和v8_5_7_1.lib。在Devtools的console里面调用时，提示错误Uncaught ReferenceError: await is not defined，无法调用。经测试在Chrome56的devtools中，是可以调用，在Chrome49中，与miniblink一样提示错误。所以我现在不知道怎么在devtools和网页中使用await，是否修正需要在mini-electron中才能使用？谢谢。

**Comment by weolar** [comment]
`<script>
const DEF_DELAY = 1000;
function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms || DEF_DELAY));
}
async function adelay(secs) { 
    await sleep(secs);
    console.log("" + secs + "ms finished");
}

adelay(10);
</script>`

上面的代码用最新的包，我亲测没问题。

**Comment by weolar** [comment]
如果你是自己编译的话，记得你代码更新到最新。而且要用release_vc6 build

**Comment by litlight** [comment]
我下载了19-3-19的最新发布版，经过测试，在Devtools中粘贴script中的代码，确实可以顺利执行。下载最新发布版最大的收获是发现支持CSS varaible了，经测试非常完美。万分感谢。

另外我又发现18-11-06版本，以及我自己编译的版本，都可以顺利执行。他们的表现是一致的，是我测试时忽略了一个问题，问题是miniblink49与chrome56的devtools在执行时有一个小的差别。
在chrome56中，执行完script中的代码后，就定义了adelay函数，可以在后面的语句中继续调用 adelay(10); await sleep(10)。
在miniblink49中，如果再次调用adelay(10)，会提示Uncaught ReferenceError: adelay is not defined(…)。如果再次调用await sleep(10)；会提示Uncaught SyntaxError: Unexpected identifier(…)。
当然这可能不是本贴最初要解决的问题了，可能是与devtools相关的问题，至于是否会对生产环境下使用await有影响，还需要在项目中做个测试。

最后，再次表示感谢。

**Comment by litlight** [comment]
我使用下面的html代码进行了实际测试，可以正常使用，多个延时函数同时执行，也不会阻塞，非常完美，Devtools报的错误，可能是因为其他原因，不会影响本函数功能的正常使用。本Issue属于使用方法问题，不属于程序本身问题。
`<html>
    <head>
        <script>
            const DEF_DELAY = 1000;
            function sleep(ms) {
                return new Promise(resolve => setTimeout(resolve, ms || DEF_DELAY));
            }
            function appendtext(secs)
            {
                var divA = document.getElementById("text");
                divA.innerHTML = divA.innerText+ "" + secs + "ms finished" ;
            }
            async function adelay(secs) {
                await sleep(secs);
                console.log("" + secs + "ms finished\n");
                appendtext(secs)
            }
        </script>
    </head>
    <body>
        <h1 >hello world</h1>
        <p id="text"></p>
        <button onclick="delayappend()">添加文本</button>
        <script>
            adelay(10000);
            adelay(1000);
            adelay(10);
        </script>

        <script>
            function delayappend()
            {
                adelay(1000)
            }
        </script>
    </body>
</html>
`

**Comment by weolar** [comment]
好的 :-)
