### ISSUE TITLE
Quasar release build does not show

### ISSUE THREAD

**Issue by Natulux** [weolar/miniblink49#254]
Hey,

I want to show a webpage, made with quasar. I tested it with the debug build, which worked quite fine. But the release build is crashing my app.
The standard backend "trident" of my wxWebview on the other hand can show both.
Can you confirm, that release does not work and maybe suggest, why this could be the case?

Thanks!

[quasarTest.zip](https://github.com/weolar/miniblink49/files/2991209/quasarTest.zip)

**Comment by weolar** [comment]
You should ues the release_vc6 build,  that is no problem.

**Comment by Natulux** [comment]
> You should ues the release_vc6 build, that is no problem.

I am pretty sure I use that.
What I meant with debug/release ist NOT the build of MiniBlink, but the build of Quasar CLI.
Quasar CLI is writing the files differently when changing the build from debug to release.

I tested further and found, that if I
- load quasar cli release build output with miniblink backend
- use javascript: "document.getElementsByTagName('html')[0].innerHTML;"
- take the returned innerHTML and use it as new "index.html" file
- load it again with miniblink backend
this does actually work.
So all that is missing in my case is some kind of refreshing the page after loading. 
I guess this is a problem that comes only with quasar, because quasar does only have js calls in its index.html and no plain html code.

**Comment by Natulux** [comment]
Ah, thank you for clarifying! I'll try that.

**Comment by Natulux** [comment]
I tested this myself and I can confirm - with the new version, release mode works.

Thank you! :-)
