### ISSUE TITLE
能否导出一个 wkeSetCursorInfoType 原因内详

### ISSUE THREAD

**Issue by shithappens2016** [weolar/miniblink49#259]
作者你好。miniblink给制作界面带来很大便利。感谢你的分享。

**1.** 用 wkeCreateWebWindow WKE_WINDOW_TYPE_TRANSPARENT 创建了层(WS_EX_LAYERED)窗口 并子类化窗口后。

**2.** 顶部最高处100px想用作标题栏。所以在窗口过程的HIT TEST里返回HTCAPTION。这当然没问题。

**3.** 标题栏下空10px的高度，下面再放一个textarea。这也没问题。

**4.** 把鼠标放在textarea里，鼠标指针变为“文本指针"，然后**快速**把鼠标移动到标题栏，这时，因为textarea与标题栏之间距离很短，wke核心很多时候没有捕捉到mouse-leave，所以鼠标到了标题栏后，指针还是“文本指针”。

如果能导出一个wkeSetCursorInfoType 的话，那么在子类化的窗口过程里HTCAPTION时就可以改变wke内部的指针了。如果直接用SetCursor的话，wke内部会瞬间改回它最后记录的指针类型。

![sdfasdf](https://user-images.githubusercontent.com/13523412/54978591-bb47fc80-4fdb-11e9-9aed-6162701efe1d.png)

#180

**Comment by weolar** [comment]
可以考虑。不过现在可以直接在CSS里写样式，就能拖拽页面了

**Comment by shithappens2016** [comment]
CSS实现拖拽试过，很棒相当便捷。只是标题栏里的按钮，点住也是可以拖动。另外，因为鼠标消息被拖拽层先捕获，所以导致按钮“被按下的效果”延迟出现。因为我需要一个异形窗口，除了窗口里的按钮（按钮不可以拖动，因为会很奇怪），其他地方都可以拖动，所以子类化了窗口。希望非常@weolar能导出这样一个api。

**Comment by weolar** [comment]
好的，下个版本加上

**Comment by shithappens2016** [comment]
@weolar 可能仅改变wke内部鼠标指针样式有点治标不治本。能否导出一个api，在HTCAPTION时，通知wke核心：目前鼠标超出它的管辖范围，不要再监控鼠标坐标并改变指针样式。

仔细看了下，不仅HTCAPTION鼠标指针没变，就连HTRIGHT HTLEFT ... 都没有改变指针。说明此时wke一直管理着指针。如果每次HIT TEST都要手动改变指针样式有些繁琐，也费性能。不如告诉wke核心：目前超出它的管理范围，放弃指针管理。这样鼠标指针管理权回归默认窗口过程也许更好些。
