### ISSUE TITLE
各种诡异

### ISSUE THREAD

**Issue by womgit** [weolar/miniblink49#275]
怀疑有内存破坏,jscallback回来的取参数,多加一行代码和不加一行代码,结果可能都不一样:成功和正确,返回值也无效.调用js也取不回返回值...

**Comment by womgit** [comment]
还发现jsValue 根本就不会释放,直到内存爆掉,只达到目的,根本不管后面什么情况...

**Comment by weolar** [comment]
基本上是你使用问题。
