### ISSUE TITLE
使用2019.7.11版本的node.dll访问https://prepaid.t-mobile.com/home会导致崩溃

### ISSUE THREAD

**Issue by HookSafe** [weolar/miniblink49#297]
@weolar 麻烦看一下是个什么情况  谢谢！

**Comment by weolar** [comment]
网站用了web worker 和MessagePort，目前mb支持的有问题导致。

**Comment by HookSafe** [comment]
> 网站用了web worker和MessagePort，目前mb支持的有问题导致。

那下个版本会修复这个问题吗？

**Comment by weolar** [comment]
你是写什么软件必须访问这个网站吗？一般这种网站，尤其还是国外的，我修复的优先级会比较低。。

**Comment by HookSafe** [comment]
> 你是写什么软件必须访问这个网站吗？一般这种网站，尤其还是国外的，我修复的优先级会比较低。。

写一个批量修改一堆账号信息的 工作量枯燥重复只能一个一个改

麻烦大佬尽快提上修复日程，小弟感激不尽！

**Comment by weolar** [comment]
好，这两天看下

**Comment by HookSafe** [comment]
> 好，这两天看下

感谢！

**Comment by weolar** [comment]
已发布
