### ISSUE TITLE
请教miniblink在 macOS 上的技术难题

### ISSUE THREAD

**Issue by AaronLeong** [weolar/miniblink49#322]
miniblink 好几年了都没有支持macOS ，但是支持了xp，所有请问在macOS上的技术问题。
我看到Typora这个submit，既然Typora用了miniblink能支持macOS，为什么miniblink不支持呢？

**Comment by weolar** [comment]
你应该看错了吧，Typora没用到miniblink。另外miniblink不支持mac的原因是我对mac下编程不太熟悉……

**Comment by AaronLeong** [comment]
> 你应该看错了吧，Typora没用到miniblink。另外miniblink不支持mac的原因是我对mac下编程不太熟悉……
不好意思，我是看到这句话猜的
`* v8值转换成list时没考虑IsNull，这个是为了修复Typora这个electron app的问题`

**Comment by weolar** [comment]
这个是mini-electron为了跑起Typora做的一次commit，还是在windows上跑的…
