### ISSUE TITLE
Ots不会使用win32版本构建，但是会使用调试模式构建。 我该怎么办 ？

### ISSUE THREAD

**Issue by WeLaJueL** [weolar/miniblink49#339]
Ots不会使用win32版本构建，但是会使用调试模式构建。 我该怎么办 ？

**Comment by weolar** [comment]
没明白啥意思……OTS这个项目编译有啥问题吗

**Comment by WeLaJueL** [comment]
是
OTS使用debug-win32构建，但不是使用Release-win32构建

**Comment by WeLaJueL** [comment]
![Capture](https://user-images.githubusercontent.com/24478963/67186960-d94ed180-f3f1-11e9-8298-9e2fecfbbb7a.PNG)

**Comment by WeLaJueL** [comment]
![Capture2](https://user-images.githubusercontent.com/24478963/67189557-18335600-f3f7-11e9-82e0-f22c163a3638.PNG)

**Comment by weolar** [comment]
要用release_vc6 配置项编译

**Comment by WeLaJueL** [comment]
非常感谢你
成功 :-)
