### ISSUE TITLE
minibink不跨平台的话跟duilib比有什么优劣势？

### ISSUE THREAD

**Issue by bigsinger** [weolar/miniblink49#353]
electron号称可以跨平台，但是看minibink的demo似乎是Windows上GUI编程，如果定位只是这样，倒还不如使用duilib：https://github.com/duilib/duilib，而且duilib写界面也简单迅速，设计也很好，关键是体积非常小，1M多点的样子。

**Comment by weolar** [comment]
mb是用html来写界面。轮子非常多。写界面也非常快。比如你要个图表啥控件，echat之类拿来就能用。duilib这类ui框架写起来太累了。我以前就是从duilib这类框架走出来的。和duilib的作者也比较熟悉。

**Comment by bigsinger** [comment]
但是minibink这样定位的话，路子就窄了，完全被electron涵盖了。electron似乎就是体积大。

**Comment by weolar** [comment]
我就是解决想用electron但又觉得体积大这个问题的。

**Comment by bigsinger** [comment]
因为不是web应用，是PC客户端的本地应用，所以体积大不大不是痛点，而且也不会定位是编写商业软件，所以不存在发布后用户因为体积大下载困难的情况。综合就是，目前这样的定位场景，其实体积倒不是痛点啦。

**Comment by weolar** [comment]
……痛点很大的，不然我也不会靠这个有商业收入

**Comment by bigsinger** [comment]
能挖掘到痛点和商业价值，那是很好的，恭喜作者。
看群已经是第九个群了，而且这个群就有一千多人，想必是有很大需求。

**Comment by weolar** [comment]
很多用delphi，c#，的人群需要个简化版的浏览器控件，我主要满足他们的需要。另外有些对内存占用比较严格、对xp有要求的人群也会来用。
还有就是部分商业软件为了提升下载安装成功率，以及减少下载CDN费用，也会对体积有要求。

**Comment by bigsinger** [comment]
明白了，我之前倒是写过一个应用，因为需要内嵌一个浏览器（摆脱IE），用duilib+cef，打包出来40M多，是很大，如果能缩减到10M左右，那肯定很happy。

对了，你可以把你上面的几个痛点提炼下，写在该项目的简介里，会更吸引眼球。

**Comment by bigsinger** [comment]
如果我不用js html写界面，仍然用duilib，加你这个mb的浏览器内核，可行吗？

**Comment by weolar** [comment]
可以呀。我这就一个dll，几个C接口的api，你可以随意嵌入

**Comment by bigsinger** [comment]
但是我需要在浏览器中执行 js 脚本， 需要js和我的c++互相调用，如果是dll的话 我没法注册这些函数。

**Comment by weolar** [comment]
没懂你的意思。我的dll有接口可以注册js和c++交互的

**Comment by bigsinger** [comment]
例如：我需要在我的cpp里注册一个自定义函数testForJS，然后在某个界面按钮交互的时候，会执行一段JavaScript脚本，脚本中有对函数testForJS的调用，执行完后JavaScript还要把结果回传给cpp。

**Comment by bigsinger** [comment]
不知道如果用mb的话 该如何下手？

另外有个小问题：mb是否提供类似cef那样的一个窗口，我只需要把mb的浏览器窗口嵌入到我的主界面中就可以了，
mb只负责渲染网址（也即充当浏览器的角色），然后并提供js与c++的互相调用，自定义注册函数。

**Comment by bigsinger** [comment]
还有一个问题是：cef的多进程模式在编程的时候其实还是很麻烦的，需要时刻注意是多进程模式，来回通信也挺麻烦。mb的浏览器这块是单进程模式还是多进程模式？

**Comment by weolar** [comment]
1，cpp里注册js，然后互相调用，这个在mb里很简单的。wkeJsBindFunction("js_notify", js_notify, (void*)app, 3);这样就注册了，然后wkeRunJS可以调用到js里。
2，mb有窗口模式和离屏摸索，窗口模式你可以指定父窗口：wkeCreateWebWindow
3，单进程的。特意解决了cef多进程的各种麻烦问题。

**Comment by bigsinger** [comment]
那蛮不错的，以上是带个node.dll就能用，还是需要就开源的代码自行修改编译？
有没有相关文档可以参考

**Comment by weolar** [comment]
直接可以用。我有个demo你可以看看，调用很简单，lib都不需要了，一个头文件一个dll就行。

**Comment by weolar** [comment]
你看下我的仓库

**Comment by bigsinger** [comment]
mb_demo.sln 这个demo吗

**Comment by weolar** [comment]
对

**Comment by bigsinger** [comment]
wkeSetWkeDllPath(&mbPath[0]);
    wkeInitialize();
    runApp(&app);
    wkeFinalize();

相当于我不调runApp了，用我自己的主窗口：
    wkeSetWkeDllPath(&mbPath[0]);
    wkeInitialize();
    //。。。。
    wkeFinalize();

这样就可以把node.dll加载起来了？但是它的浏览器窗口句柄在哪里

**Comment by weolar** [comment]
有接口可以取。
