### ISSUE TITLE
跨域问题 iframe

### ISSUE THREAD

**Issue by yuanbi** [weolar/miniblink49#358]
我在一个页面中跨域访问iframe的document , 我关闭了跨域检查 , 访问数据等等都没问题 , 当我调用iframe中的标签的click()方法的时候却不成功 , 在chrome中打开F12切换当前域为目标iframe调用标签的click()方法没问题 , 用同样的方法在vip-miniblink.exe中却无效 , 这个问题有办法解决吗

**Comment by weolar** [comment]
一般来说，这是你js写的有问题。

**Comment by yuanbi** [comment]
> 一般来说，这是你js写的有问题。

我也希望是我的代码的问题,可是在chrome上却正常
