### ISSUE TITLE
我想在页面完整的加载结束后,再将页面显示出来,我该怎么做,我的代码进入了无限循环

### ISSUE THREAD

**Issue by yuanbi** [weolar/miniblink49#359]
本来想在论坛发这个问题的,论坛的验证码加载不出来....

`	bool isLoad = false;
	do{
		isLoad = wkeIsDocumentReady(window);
		Sleep(1000);
	}while(!isLoad);

	jsExec = wkeGlobalExec(window);
	jsEvalW(jsExec,jsGetAdsUrlG);
	jsEvalW(jsExec,L"loaddone = 15;window.onload = function (){loaddone = 1;}");

	jsValue jsRet;
	int ret = 0;
	do 
	{
		jsRet = jsEvalW(jsExec,L"return loaddone;");
		ret = jsToInt(jsExec, jsRet);
		Sleep(1000);
	} while (ret == 15);
`

wkeIsDocumentReady永远返回false
注释掉wkeIsDocumentReady判断代码时
jsEvalW 永远返回15

**Comment by yuanbi** [comment]
document.readyState 解决

**Comment by weolar** [comment]
其实我有个回调的api……

**Comment by yuanbi** [comment]
> 其实我有个回调的api……

我还有个问题,在主线程没有窗口的情况下,使用Sleep等待网页加载卡主的问题,我目前的解决方法是主线程创建隐藏窗口,创建线程发送消息与主线程通信,我可以不创建窗口的情况下解决这个问题吗

**Comment by weolar** [comment]
搞不懂为啥你要sleep，正常消息循环不就好了吗

**Comment by yuanbi** [comment]
> 搞不懂为啥你要sleep，正常消息循环不就好了吗

我没有主窗口,所以没有消息循环

**Comment by weolar** [comment]
这和你有没窗口没关系。我这是个正常的windows程序，没消息循环我内部怎么调度各种windows相关的操作

**Comment by yuanbi** [comment]
> 这和你有没窗口没关系。我这是个正常的windows程序，没消息循环我内部怎么调度各种windows相关的操作

了解了,谢谢指点
