### ISSUE TITLE
鼠标滑动，页面元素未跟随鼠标一起移动

### ISSUE THREAD

**Issue by cppfuns** [weolar/miniblink49#360]
![image](https://user-images.githubusercontent.com/7980920/71650279-ce001680-2d4f-11ea-8ae3-216f38e1f5e6.png)

https://www.html5tricks.com/demo/js-passwd-generator/index.html

版本 75.0.3770.142（正式版本） （64 位） 正常跟随

miniblink-200101 vip-miniblink.exe复现

**Comment by weolar** [comment]
查了下，是style="--x:332px; --y:47px;"这个写法不支持

**Comment by cppfuns** [comment]
属于合法得语法么？mb会支持么？
