### ISSUE TITLE
源码 缺 wkeScreenshot 等12个 函数的实现 请补全

### ISSUE THREAD

**Issue by shithappens2016** [weolar/miniblink49#362]
源码里缺了一下几个函数的实现：

```cpp
wkeShutdownForDebug

wkeIsWebviewValid

wkeClearCookie

wkeSetStringWithoutNullTermination

wkeCreateStringWithoutNullTermination

wkeGetStringLen

wkeScreenshot

wkeNetGetRawHttpHead

wkeNetGetRawResponseHead

wkePluginListBuilderAddPlugin

wkePluginListBuilderAddMediaTypeToLastPlugin

wkePluginListBuilderAddFileExtensionToLastMediaType
```

**Comment by weolar** [comment]
新功能不再提供源码了

**Comment by shithappens2016** [comment]
@weolar 
``` wkeClearCookie ``` should be implemented anyway.

**Comment by weolar** [comment]
这个的实现很简单：
void WKE_CALL_TYPE wkePerformCookieCommand(wkeWebView webView, wkeCookieCommand command)
{
    WKE_CHECK_WEBVIEW_AND_THREAD_IS_VALID(webView, (void)0);
    CURL* curl = curl_easy_init();
    if (!curl)
        return;

    std::string cookiesPath = webView->getCookieJarPath();
    CURLSH* curlsh = webView->getCurlShareHandle();

    curl_easy_setopt(curl, CURLOPT_SHARE, curlsh);
    curl_easy_setopt(curl, CURLOPT_COOKIEJAR, cookiesPath.c_str());
    
    switch (command) {
    case wkeCookieCommandClearAllCookies: {
        curl_easy_setopt(curl, CURLOPT_COOKIELIST, "ALL");
        std::wstring cookiesPathW = base::UTF8ToWide(cookiesPath);
        ::DeleteFileW(cookiesPathW.c_str());
    }
        break;
    case wkeCookieCommandClearSessionCookies:
        curl_easy_setopt(curl, CURLOPT_COOKIELIST, "SESS");
        break;
    case wkeCookieCommandFlushCookiesToFile:
        curl_easy_setopt(curl, CURLOPT_COOKIELIST, "FLUSH");
        break;
    case wkeCookieCommandReloadCookiesFromFile:
        curl_easy_setopt(curl, CURLOPT_COOKIELIST, "RELOAD");
        break;
    }
    curl_easy_cleanup(curl);
}

void wkeClearCookie(wkeWebView webView)
{
    wkePerformCookieCommand(webView, wkeCookieCommandClearAllCookies);
}

**Comment by shithappens2016** [comment]
@weolar
感谢提供代码 学习了
