### ISSUE TITLE
Layer Js插件嵌套时出现bug

### ISSUE THREAD

**Issue by wsteel** [weolar/miniblink49#371]
测试版本： 2020.2.7版
下面代码进行测试， chrome中表现正常。
wkexe.exe中 prompt弹出后，点击prompt标题会自动消失，date点击后不显示。 
wkexe_x64.exe中会直接崩溃退出。

[testlayer.zip](https://github.com/weolar/miniblink49/files/4243487/testlayer.zip)

**Comment by weolar** [comment]
好的我康康

**Comment by weolar** [comment]
@wsteel 感谢，已经修复。等下个版本带出。是上个版本我大幅优化css动画性能导致的问题

**Comment by wsteel** [comment]
2020.3.3 版本已无问题，感谢您辛苦的付出！
