### ISSUE TITLE
建议补充支持 SVG 2 的 href 属性

### ISSUE THREAD

**Issue by cai-niao** [weolar/miniblink49#379]
## 现象
用 20200312 版本包中 vip_miniblink.exe 访问 https://panjiachen.gitee.io/vue-element-admin/ 时，发现网页中的小图标显示不正常，换用用其他浏览器都没有问题。

## 分析
通过开发者工具，发现问题页面使用了 SVG Spirit 技术来显示图标，具体为利用`<symbol>`和`<use>`元素配合进行图标显示。

初步怀疑 miniblink 对`<symbol>`和`<use>`元素支持有限，故专门在 MDM 找到示例代码来测试，却发现一切正常（测试代码来自： https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol ）

最终对比测试发现，问题网页的`<use>`元素使用了 href 属性，MDM 示例代码使用了 xlink:href 属性。miniblink 支持 SVG 1 的 xlink:href 属性，但不支持 SVG 2 的 href 属性。

因 MDM 建议使用 SVG 2 的 href 属性，SVG 1 的 xlink:href 属性已废弃不推荐使用，故向 miniblink 建议补充支持 SVG 2 的 href 属性。（相关文档： https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href 、 https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href ）

## 复现
使用以下代码可观察到，miniblink 不能显示中间的第三个圆，其他浏览器显示正常。
```
<html>
<head></head>
<body>
<svg viewBox="0 0 80 20" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
  <!-- Our symbol in its own coordinate system -->
  <symbol id="myDot" width="10" height="10" viewBox="0 0 2 2">
    <circle cx="1" cy="1" r="1" />
  </symbol>
 
   <!-- A grid to materialize our symbol positioning -->
  <path d="M0,10 h80 M10,0 v20 M25,0 v20 M40,0 v20 M55,0 v20 M70,0 v20" fill="none" stroke="pink" />
 
  <!-- All instances of our symbol -->
  <use xlink:href="#myDot" x="5"  y="5" style="opacity:1.0" />
  <use xlink:href="#myDot" x="20" y="5" style="opacity:0.8" />
  <use href="#myDot" x="35" y="5" style="opacity:0.6" /><!-- 此处使用 href 属性 -->
  <use xlink:href="#myDot" x="50" y="5" style="opacity:0.4" />
  <use xlink:href="#myDot" x="65" y="5" style="opacity:0.2" />
</svg>
</body>
</html>
```

**Comment by weolar** [comment]
好的，我研究一下

**Comment by cai-niao** [comment]
大神辛苦啦！

另外发现，miniblink 访问 [MDN 的页面](https://developer.mozilla.org/zh-CN/docs/Web) 会提示“内容呈现出错”，开发者工具中有关于 `document.querySelectorAll` 的错误，估计是高版本 JS 的兼容性问题。

**祝愿 miniblink 能发展得越来越好！**

**Comment by weolar** [comment]
感谢支持，蛤蛤

**Comment by weolar** [comment]
好了，herf那个问题修复了。MDN这个，是因为用了symbol.iterator，这个ES6的东西，目前mb因为v8还是5.7版本，所以不支持

**Comment by cai-niao** [comment]
半夜加班辛苦了！期待大神的新版本~
最近在尝试用 miniblink + C# 开发一个业余的桌面程序，感觉很不错~
