### ISSUE TITLE
MsgBox on termiante app

### ISSUE THREAD

**Issue by Natulux** [weolar/miniblink49#385]
Hey
I used a HTTP server along side miniblink. The user was able to click a button on the webpage, sending a query to the app with the embedded browser and the app would should down.
I changed the server to HTTPS for security purposes, but now I get message that I am unable to read.

Can you translate that for me and/or give a hint where and why that message is shown?
Thank you so much!

![msgBox](https://user-images.githubusercontent.com/12150971/79343625-e8d94e00-7f2e-11ea-9722-77b618c22326.png)

**Comment by weolar** [comment]
it means,  you call wkeGlobalExec on other thread.
miniblink only allow call api on main thread

**Comment by Natulux** [comment]
Oh I see. Yes, the HTTPS server is multi threaded and thus the call to end the session arrives in a worker thread.
Funny though, because the HTTP server was also multi threaded and that worked just fine.
I will see if I can delegate my call to the main thread. Thanks

**Comment by weolar** [comment]
yes, you can delegate  your call to the main thread.

**Comment by Natulux** [comment]
Found it - the call to wkeGlobalExec in that situation was not needed anyway.
Thank you for your quick and helpful support!
