### ISSUE TITLE
请问有编译好的bin,lib库吗？

### ISSUE THREAD

**Issue by litterbug23** [weolar/miniblink49#42]
之前一直用wke，但是wke没有64位，cef又太庞大了，感谢weolar提供的小巧的cef版本，还暖心的提供了wke接口。

**Comment by weolar** [comment]
多谢支持~
现在miniblink已经有64版本了。不过目前版本处于大变动过程中（在增加node版、渲染架构也在调整），所以不方便提供bin、lib。等稳定下来就会定期上传bin了。或者你加178168957群吧。里面我经常会传最新的版本bin

**Comment by zero-ui** [comment]
最近已经把bin文件添加上了

**Comment by zoand** [comment]
加群还没有通过，这个核编译出来有多大？

**Comment by weolar** [comment]
最小版本12M。带node版本18M
