### ISSUE TITLE
关于C#调用wkeNetChangeRequestUrl提示“尝试读取或写入受保护的内存。这通常指示其他内存已损坏。”

### ISSUE THREAD

**Issue by wally94** [weolar/miniblink49#423]
c# 调用wkeNetChangeRequestUrl 时提示：

System.AccessViolationException
  HResult=0x80004003
  Message=尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
  Source=<无法计算异常源>
  StackTrace:
<无法计算异常堆栈跟踪>

如何解决？

**Comment by weolar** [comment]
这个肯定是你使用上的问题导致。

**Comment by wally94** [comment]
其他API没有出现问题，就是这个出现了这个问题，也尝试使用了例程NetMiniblink，同样也是有这个问题，不知道应该如何使用此接口

**Comment by wally94** [comment]
已找出原因：
此接口头文件中定义是void，实际返回int：0，1
ITERATOR2(void, wkeNetChangeRequestUrl, wkeNetJob jobPtr, const char* url, "")\

**Comment by weolar** [comment]
显然不是返回值的问题。而且这个返回值就是void

**Comment by wally94** [comment]
官网更新的最新官方例程中代码如下
  [DllImport("node.dll", EntryPoint = "wkeNetChangeRequestUrl", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi)]
        public static extern byte wkeNetChangeRequestUrl(IntPtr job, string url);

**Comment by weolar** [comment]
我只维护内核代码，以及C++，其他所以其他语言都是别人写的。使用时请自行参考最新wke.h里面的api
