### ISSUE TITLE
jsBindFunction 不规律的失效

### ISSUE THREAD

**Issue by sunxu888** [weolar/miniblink49#435]
我是在加载页面前声明的，但是有时候不管用，控制台会报错  xxxx is not defined

但是我按f5 刷新了页面就可以了，请问是什么问题

**Comment by weolar** [comment]
这个api只能用一次，就是初始化完毕之后。

**Comment by sunxu888** [comment]
当我程序启动的时候，有时候不管用，有时候管用，我只声明了一次。
不管用的时候，我刷新一下页面就管用了，很疑惑

**Comment by weolar** [comment]
你要在加载页面前调用才行。而且是一初始化完毕后就调用jsBindFunction

**Comment by sunxu888** [comment]
我是照做的，那我自己再找找原因

**Comment by sunxu888** [comment]
多谢哦
