### ISSUE TITLE
新手第一个示例窗口空白，且没反应，求助

### ISSUE THREAD

**Issue by GitHubAccou** [weolar/miniblink49#442]
代码如下：
``#include "wke.h"
#include <iostream>
using namespace std;

void handleDocumentReady(wkeWebView webWindow, void* param)
{
    wkeShowWindow(webWindow, true);
}
int main(){
	wkeSetWkeDllPath(L"E:/download/miniblink-20200824/miniblink_x64.dll");
	wkeInitialize();
	wkeWebView ww=wkeCreateWebWindow(WKE_WINDOW_TYPE_POPUP,NULL,0,0,1366,768);
	wkeSetWindowTitle(ww,"Miniblink GUI程序");
	wkeOnDocumentReady(ww, handleDocumentReady, NULL);
	// wkeOnLoadUrlEnd(ww,onLoadUrlEnd,NULL);
	wkeLoadURL(ww,"https://www.baidu.com");
	wkeShowWindow(ww,true);
	while(true){
		Sleep(1000);
		cout << "wait" <<endl;
	}
}

**Comment by yulon** [comment]
把 while Sleep 换成消息循环，没有消息循环人家动不起来啊

**Comment by GitHubAccou** [comment]
最后调用wkeRunMessageLoop(),
