### ISSUE TITLE
Does miniblink supports turn off server name indication

### ISSUE THREAD

**Issue by dylech30th** [weolar/miniblink49#445]
I'm looking for an embedded browser framework which supports disable SNI during SSL handshake to achieve some special purpose, and as far as I know, none of those most widely used frameworks support this functionality (and they are also too heavy to use)

**Comment by weolar** [comment]
yes, miniblink supports turn off.
miniblink send net request by openssl. you can modify the openssl code to turn off it.

**Comment by dylech30th** [comment]
sorry for the late and the unfamiliar with OpenSSL/Chromium, thus I'm wondering if I need to modify the source myself and compile it, or whether there're some sort of switches or APIs that can offer this functionality?
