### ISSUE TITLE
第一次加载动画WKE_LOADING_SUCCEEDED消息渲染闪白问题

### ISSUE THREAD

**Issue by zym479466697** [weolar/miniblink49#451]
为什么第一次加载动画等待WKE_LOADING_SUCCEEDED消息后立马切换到网页控件闪白 
按理来说这时候已经加载完成了 渲染应该有东西了 但是会闪白一下

**Comment by weolar** [comment]
因为渲染的东西需要异步绘制上来

**Comment by zym479466697** [comment]
> 因为渲染的东西需要异步绘制上来

那我要什么时机从我的加载界面切换到网页 才不会出现闪白过度？

**Comment by zym479466697** [comment]
> 因为渲染的东西需要异步绘制上来
那我改成第一次渲染完成 在切换吧
