### ISSUE TITLE
WebGL支持问题

### ISSUE THREAD

**Issue by koangel** [weolar/miniblink49#456]
测试4399小游戏。依赖WEBGL的游戏无法运行，提示：

Your browser does not support WebGL
OK

有什么办法搞定么？
![QQ截图20201122100846](https://user-images.githubusercontent.com/4347091/99891985-f2881880-2caa-11eb-9a8d-92ad6469fee6.png)

**Comment by koangel** [comment]
测试地址：http://www.4399.com/flash/216716_1.htm

**Comment by weolar** [comment]
vip版支持webgl。不过也无法开启硬件加速模式。这种小游戏类型的网页不建议用miniblink

**Comment by koangel** [comment]
好的 谢谢，我没用VIP版，那估计不行了，我用CEF吧
