### ISSUE TITLE
Chrome DevTools Protocol

### ISSUE THREAD

**Issue by lexesv** [weolar/miniblink49#458]
Hello.
Does miniblink49 support this protocol?
For example, if Chrome is running with --remote-debugging-port=9222 the debugger URL can be found at localhost:9222/json.

**Comment by weolar** [comment]
no, devtools remote debug protocol is removed....




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weolar/miniblink49"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月20日(星期天) 凌晨0:34
收件人:&nbsp;"weolar/miniblink49"<miniblink49@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[weolar/miniblink49] Chrome DevTools Protocol (#458)





 
Hello.
 Does miniblink49 support this protocol?
 For example, if Chrome is running with --remote-debugging-port=9222 the debugger URL can be found at localhost:9222/json.
