### ISSUE TITLE
document.getElementsByName can't set value

### ISSUE THREAD

**Issue by mark-lobanov** [weolar/miniblink49#465]
Hello

I'm try to call JS code `document.getElementsByName("password")[0].value = "strong_password"` but when I select the password fileld it's value becomes empty

I use Delphi wrapper https://gitee.com/LangjiApp/Wke4Delphi
My code: `WB.ExecuteJavascript('document.getElementsByName("password")[0].value = "strong_password"');`

```
function TWkeWebCore.ExecuteJavascript(const js: string): boolean;
var
  newjs: AnsiString;
  r    : jsValue;
  es   : jsExecState;
begin
  result := false;
  newjs  := 'try { ' + js + '; return 1; } catch(err){ return 0;}';
  if Assigned(theWebView) then
  begin
    r  := wkeRunJS(theWebView, PansiChar(ansitoutf8(newjs)));
    es := wkeGlobalExec(theWebView);
    if jsIsNumber(r) then
    begin
      if jsToint(es, r) = 1 then
        result := true;
    end;
  end;
end;
```
node.dll version 2020.11.25.0

https://user-images.githubusercontent.com/20513479/103277763-687e4e80-49d2-11eb-9d41-23a840dae39f.mp4

test with url:
`https://auth-preprod.ehealth.gov.ua/sign-in?client_id=9a1269f7-b001-43fb-bc8c-32ca4ce80a36&redirect_uri=https://eh-srv-preprod.mcmed.ua/&scope=capitation_report:read client:read connection:delete connection:read connection:refresh_secret connection:write contract:read contract:write contract_request:approve contract_request:create contract_request:read contract_request:sign contract_request:terminate declaration:read declaration_request:approve declaration_request:read declaration_request:reject declaration_request:write division:activate division:deactivate division:details division:read division:write employee:deactivate employee:details employee:read employee:write employee_request:approve employee_request:read employee_request:reject employee_request:write employee_role:read employee_role:write healthcare_service:read healthcare_service:write legal_entity:read medication_dispense:read medication_request:details otp:read otp:write person:read reimbursement_report:read related_legal_entities:read secret:refresh&email=markl@ukr.net&response_type=code
`

**Comment by hd2y** [comment]
I tested it in the browser and the results were the same, so I didn't think there was any problem with Miniblink.

**Comment by mark-lobanov** [comment]
I replaced my code with
`WB.ExecuteJavascript('document.forms[0].password.focus();document.forms[0].password.value="strong_password";');`
and problem is gone

What's the difference ih javascript ?


Here is this HTML-element:
![зображення](https://user-images.githubusercontent.com/20513479/103439360-e053af80-4c44-11eb-88eb-9bf8c46b53b9.png)

**Comment by hd2y** [comment]
![image](https://user-images.githubusercontent.com/26451172/103511401-f6aa7700-4ea1-11eb-9b00-0f19fb59977b.png)
You can check on this.

**Comment by mark-lobanov** [comment]
it's uncritically issue, you can close it
thank you
