### ISSUE TITLE
google captcha localization

### ISSUE THREAD

**Issue by mark-lobanov** [weolar/miniblink49#469]
Hello

I'm loading web page with google captcha by url
`https://auth-preprod.ehealth.gov.ua/sign-in?client_id=9a1269f7-b001-43fb-bc8c-32ca4ce80a36&redirect_uri=https://eh-srv-preprod.mcmed.ua/&scope=capitation_report:read client:read connection:delete connection:read connection:refresh_secret connection:write contract:read contract:write contract_request:approve contract_request:create contract_request:read contract_request:sign contract_request:terminate declaration:read declaration_request:approve declaration_request:read declaration_request:reject declaration_request:write division:activate division:deactivate division:details division:read division:write employee:deactivate employee:details employee:read employee:write employee_request:approve employee_request:read employee_request:reject employee_request:write employee_role:read employee_role:write healthcare_service:read healthcare_service:write legal_entity:read medication_dispense:read medication_request:details otp:read otp:write person:read reimbursement_report:read related_legal_entities:read secret:refresh&email=markl@ukr.net&response_type=code`

Whole page is in Ukrainian but the captcha is in Chinese
How I can show it in other language (in Ukrainian e.g. or English) ?
node.dll version is 2020.11.25.0

![image](https://user-images.githubusercontent.com/20513479/103540947-40e02800-4ea3-11eb-9ce7-475ea249df18.png)

**Comment by mark-lobanov** [comment]
IMHO captcha must be in the same language with document language

**Comment by mark-lobanov** [comment]
?

**Comment by mark-lobanov** [comment]
这个问题会解决吗？

**Comment by weolar** [comment]
看了下，应该是http 请求头里使用了zh-cn吧。我需要加个接口，能让外部设置这个语言信息

**Comment by mark-lobanov** [comment]
请添加此界面
please, add this interface

**Comment by weolar** [comment]
@mark-lobanov   hi, I find the inteface “wkeSetLanguage”  could  resolve your problem

**Comment by mark-lobanov** [comment]
It works, thanks !
