### ISSUE TITLE
刚才试了下好像是不支持WebAssembly的站点

### ISSUE THREAD

**Issue by lhtuling** [weolar/miniblink49#475]
https://wasm.blazor.zone/
会报错

![image](https://user-images.githubusercontent.com/44140500/107143705-847df400-6971-11eb-8b2d-8f1e57ed1d77.png)

如果是的话   这个有计划支持么

**Comment by weolar** [comment]
会支持的，大概春节后。目前v8已结升级到7.5版本了。就是这个import要实现得改blink，比较麻烦。
