### ISSUE TITLE
SetDebugConfig方法调用无法赋值

### ISSUE THREAD

**Issue by MrQiangHu** [weolar/miniblink49#482]
![image](https://user-images.githubusercontent.com/47696941/113343825-e4d25600-9362-11eb-98d8-90873c587b84.png)
上述两个方法

**Comment by MrQiangHu** [comment]
第二个无论等待延迟获取还是怎样值都为NULL

**Comment by MrQiangHu** [comment]
我就是想设置浏览器为无图模式，设置不了

**Comment by jiukouyin** [comment]
可以根据扩展名拦截 然后WkeCancelRequest

**Comment by MrQiangHu** [comment]
非常感谢！
