### ISSUE TITLE
VIP

### ISSUE THREAD

**Issue by lexesv** [weolar/miniblink49#483]
@weolar how can I buy a personal VIP version?
I cannot contact you. You have not responded by email.
I don't have a QQ messenger.

**Comment by 996666925** [comment]
It is suggested to register a QQ number and then join the QQ group 94093808.

**Comment by lexesv** [comment]
Unfortunately, I cannot register a QQ number. Why not use a common messenger, for example Telegram?

**Comment by weolar** [comment]
@lexesv  hi，our Telegram is https://t.me/miniblink
