### ISSUE TITLE
用vs2015编译链接失败：fatal error LNK1181: 无法打开输入文件“ots.lib”

### ISSUE THREAD

**Issue by gxlmyacc** [weolar/miniblink49#52]
你好，用vs2015编译链接失败：fatal error LNK1181: 无法打开输入文件“ots.lib”，
请问下这个怎么解决？

**Comment by weolar** [comment]
工程里不是有ots的工程吗，编译即可。不过最近工程配置在大改，就算编过，也跑不起来···

**Comment by gxlmyacc** [comment]
恩，确实编译不了，最后提示编译失败： fatal error LNK1120: 427 个无法解析的外部命令
最后，建议给miniblink项目设置下依赖项，这样只要编译miniblink就可以了。

**Comment by weolar** [comment]
我刚把release_vc6配置的整理好，现在在整理release的。你等等再编译
