### ISSUE TITLE
由于本项目被黑产拿去修改源码后用于非法目的，已经违背我当初开源的原意

### ISSUE THREAD

**Issue by lanmanck** [weolar/miniblink49#531]
哥你好搞笑，开源还这么叽歪，他拿去擦屁股你同意不？

**Comment by weolar** [comment]
我特么以前被各个公司的安全部门找上门的时候，你这种人只会说风凉话。

**Comment by lanmanck** [comment]
那咱们用盗版windows攻击银行、政府，怎么没见他们找微软呢？

**Comment by tonyxty** [comment]
@lanmanck 我觉得不如拿来擦擦你的嘴，好好的嘴怎么在喷粪呢
