### ISSUE TITLE
请问该怎么做才能支持音视频?

### ISSUE THREAD

**Issue by amhoho** [weolar/miniblink49#56]
这个好像被你删了?怎么补回,不差这一点容量啊

**Comment by zero-ui** [comment]
加上音视频会多几M，不差容量你可以选择cef😏

**Comment by zero-ui** [comment]
另外音视频可以用flash替代，并不是刚需

**Comment by wony-zheng** [comment]
这个好，我就想找个没有音视频的内核，音视频直接引入ffmpeg就好

**Comment by zhanjx1314** [comment]
可以试试vlc npapi的插件

发自我的 iPhone

在 2017年4月22日，上午9:37，wony <notifications@github.com<mailto:notifications@github.com>> 写道：


这个好，我就想找个没有音视频的内核，音视频直接引入ffmpeg就好
