### ISSUE TITLE
ARM32 构建

### ISSUE THREAD

**Issue by DellZHackintosh** [weolar/miniblink49#569]
不错的项目！如果这个项目可以构建 ARM32 版本的话，那对濒临死亡的一众 Windows ARM32 设备来说是很好的🙂

**Comment by weolar** [comment]
这年头还有人用windows ARM32么……

**Comment by DellZHackintosh** [comment]
当……然。既然我开了这个 issue，那么至少我是在用的。
不过当然也有其他人。我们都希望可以让老设备发挥余热。
不过，如果实现这个有难度或者您觉得没必要的话，那不搞也没关系。ARM32 被微软抛弃了这么多年，不管再做什么工作都只能让它们多喘会气了……

**Comment by weolar** [comment]
我之前搞了把miniblink跑在nt4上面。如果你有需要我也可以研究下ARM32。只不过我好像没找到ARM32的虚拟机

**Comment by weolar** [comment]
不客气。我看ARM64好像还是有一些人在用的。ARM32真没看到人用过。没有虚拟机那感觉我搞不了了，调试太麻烦了

**Comment by weolar** [comment]
话说你是真机测试这个ARM32？

**Comment by DellZHackintosh** [comment]
> 我看ARM64好像还是有一些人在用的。

毕竟已经有针对消费者的产品了。不过这个因为自带转译指令所以跑程序没啥问题。
ARM32的话，都是早年产品了，Surface RT/2 和 一大堆 Lumia 手机。已死。

> 话说你是真机测试这个ARM32？

说得好听点是这样吧，不过严格意义上来说我是在拿它（ARM设备）在日用😂
***
如果搞不来也没关系，谢谢您的回复。
