### ISSUE TITLE
Anyone please help to build miniblink49 Lite branch

### ISSUE THREAD

**Issue by mediaexplorer74** [weolar/miniblink49#580]
Today I tried to assemble miniblink49 Lite branch.
2 projects (ots, miniblink) failed to compile...

I use newest VS 2022 Preview.

If you're experienced C++ developer please try to repeat my way... and explain the bugs you meet...

My goal is:
 transform MiniBlink into some useful uwp web browser for old sweet Lumia phones (Windows 10 Mobile os) 

Best wishes,
MediaExplorer

**Comment by weolar** [comment]
Sorry, I just saw the message.
What error did you encounter when compiling?

**Comment by zero-rp** [comment]
The lite branch has been discontinued, please compile with the master branch

**Comment by mediaexplorer74** [comment]
> Sorry, I just saw the message. What error did you encounter when compiling?

Thank you. I decided to cancel all my MiniBlink49's plans. I closed this issue. Sorry
