### ISSUE TITLE
建议官方出一款能运行miniblink的嵌入式硬件

### ISSUE THREAD

**Issue by xiongsongsong** [weolar/miniblink49#83]
1. 整个硬件围绕以最快速度加载并运行miniblink为目标。
3. 搭配一款触摸屏，blink以适配触摸模式启动。

blink是最好的UIKit，没有之一。如此，很有可能开创性的发明出 miniblink wear等概念设备，并且能大卖，造福广大前端或软件工程师。

**Comment by xiongsongsong** [comment]
现阶段替代electron的场景，无非是锦上添花，并不是开创性工作。将chromium移植到嵌入式设备上，会更有价值。

**Comment by weolar** [comment]
现在只是个开源公益项目，暂时没精力做硬件，先把pc版本做稳定为第一目的；不过如果有人能投资，移植到嵌入式并且配合硬件去卖，那我还是很欢迎的

**Comment by tonymiao2012** [comment]
兄弟，可否加入你的项目做贡献？

**Comment by weolar** [comment]
可以啊，欢迎加入。加178168957群一起讨论吧
