### ISSUE TITLE
提一点关于编译选项的建议

### ISSUE THREAD

**Issue by darkskygit** [weolar/miniblink49#89]
建议把“优化”选项卡里除了“优化”这一项外的选项还原成默认，除了miniblink外的项目打开全程序优化，然后“代码生成”里的“启用字符串池”和“启用函数级链接”也可以还原成默认值
![1](https://user-images.githubusercontent.com/25152247/38181106-9b63d9ee-3663-11e8-8346-0c86b663f9be.png)
![image](https://user-images.githubusercontent.com/25152247/38181268-851e46f0-3664-11e8-941c-1acfaee40aaf.png)
原因是根据msdn的说明，“最大优化（优选大小）”已经包含了这几个工程里手工修改的选项：
![image](https://user-images.githubusercontent.com/25152247/38181178-0f9ae28a-3664-11e8-9c11-113afb61a91b.png)

**Comment by darkskygit** [comment]
https://msdn.microsoft.com/en-us/library/8f8h5cxt.aspx
msdn说明在这里

**Comment by darkskygit** [comment]
https://msdn.microsoft.com/en-us/library/8f8h5cxt.aspx
msdn说明在这里

**Comment by darkskygit** [comment]
还有建议使用“引用”功能对编译出来的静态库进行依赖，这样就不需要手工修改链接依赖项了
![image](https://user-images.githubusercontent.com/25152247/38181657-b6d663ba-3666-11e8-811a-e532c29a7e48.png)

**Comment by weolar** [comment]
关于编译依赖，其实是故意不加依赖的。因为那些lib几万年可能都不会编译一次，加了后每次启动调试都非常慢。而且目前也没什么编译依赖，先编译其他几个lib，最后miniblink主工程就行了。

**Comment by zero-rp** [comment]
设置依赖项后会影响调试编译速度
