### ISSUE TITLE
能否添加webp支持

### ISSUE THREAD

**Issue by sndwow** [weolar/miniblink49#91]
miniblink主要是用于嵌入式组件，大量采用webp作为图片格式，打包到应用中，可以很有效的解决应用大小问题，希望能加入。

**Comment by weolar** [comment]
主要是webp的解码库有点大，所以没带了。而且网站很少用到。如果需要，可以自己加上

**Comment by sndwow** [comment]
了解，感谢回复。这个项目相当赞！

**Comment by weolar** [comment]
现在你们项目需要webp吗

**Comment by sndwow** [comment]
因为用到很多图片素材，所以就想着用webp来减小体积

**Comment by sndwow** [comment]
不知道加了webp解码后，体积会增加多少？

**Comment by weolar** [comment]
好像增加2m多。其实你可以用svg来代替。如果实在要用webp，就改下third_party\WebKit\Source\platform\image-decoders\ImageDecoder.cpp
里的代码添加webp支持

**Comment by sndwow** [comment]
主要是动图比较多，好像不支持转换成svg吧？

**Comment by sndwow** [comment]
官方能加上就更好了，自己不会加  😆。

**Comment by weolar** [comment]
暂时不想加，因为类似的需求太多了，有的不要openssl，有的不要node，有的连任何解码库都不想要……我都不知道听谁好。所以现在只提供一个不带node的小巧版，和一个基本都带的完整版
