### ISSUE TITLE
GetBydefaultVal没有此函数

### ISSUE THREAD

**Issue by FEI17N** [weolar/miniblink49#94]
GetBydefaultVal没有此函数

编译文件位置
ApiWindow.cpp

**Comment by weolar** [comment]
请仔细看首页里的编译指南，这两工程不需要编译

**Comment by FEI17N** [comment]
编译指南中说编译其他所有项目 
但是
严重性	代码	说明	项目	文件	行
错误	LNK1104	无法打开文件“node.lib”	cefclient	F:\WORK\ExtraLib\miniblink49\build\cefclient\LINK	1

严重性	代码	说明	项目	文件	行
错误	C2039	“GetBydefaultVal”: 不是“gin::Dictionary”的成员	electron	f:\work\extralib\miniblink49\electron\browser\api\apiwindow.cpp	1586

严重性	代码	说明	项目	文件	行
错误	C2039	“GetBydefaultVal”: 不是“gin::Dictionary”的成员	electron	f:\work\extralib\miniblink49\electron\browser\api\apiwindow.cpp	1586

且只编译4.8不行 会出现
严重性	代码	说明	项目	文件	行
错误	LNK1181	无法打开输入文件“v8_5_7.lib”	miniblink	F:\WORK\ExtraLib\miniblink49\build\miniblink\LINK	1

但是5.7会出现
严重性	代码	说明	项目	文件	行
错误	C2039	“GetBydefaultVal”: 不是“gin::Dictionary”的成员	electron	f:\work\extralib\miniblink49\electron\browser\api\apiwindow.cpp	1610

而且没有项目名字叫node
