### ISSUE TITLE
debug下多项编译问题

### ISSUE THREAD

**Issue by FEI17N** [weolar/miniblink49#98]
编译指南中说编译其他所有项目
但是
严重性	代码	说明	项目	文件	行
错误	LNK1104	无法打开文件“node.lib”	cefclient	F:\WORK\ExtraLib\miniblink49\build\cefclient\LINK	1

严重性	代码	说明	项目	文件	行
错误	C2039	“GetBydefaultVal”: 不是“gin::Dictionary”的成员	electron f:\work\extralib\miniblink49\electron\browser\api\apiwindow.cpp	1586

且只编译4.8不行 会出现
严重性	代码	说明	项目	文件	行
错误	LNK1181	无法打开输入文件“v8_5_7.lib”	miniblink	F:\WORK\ExtraLib\miniblink49\build\miniblink\LINK	1

但是5.7会出现
严重性	代码	说明	项目	文件	行
错误	C2039	“GetBydefaultVal”: 不是“gin::Dictionary”的成员	electron f:\work\extralib\miniblink49\electron\browser\api\apiwindow.cpp	1610

而且没有项目名字叫node

**Comment by FEI17N** [comment]
严重性	代码	说明	项目	文件	行
错误	C2039	“GetBydefaultVal”: 不是“gin::Dictionary”的成员	electron f:\work\extralib\miniblink49\electron\browser\api\apiwindow.cpp	1586

这一条可以不用管 但是里面的问题绕不开

**Comment by zero-rp** [comment]
node项目就是miniblink项目

**Comment by weolar** [comment]
请仔细看编译说明
